#!/bin/sh
PWD="$(cd $(dirname $0) && pwd)"

usage() {
    echo "ERROR: action missing"
    echo "syntax: $0 <start|stop|restart|status|config|install|uninstall>"
    echo "example: $0 start"
}

start() {
    ls
}

stop() {
    ls
}

run() {
    custom_u -c $PWD/conf/custom.conf -w $PWD
}

set_config() {
    ls
}

if [ $# -lt 1 ]; then
    usage
    exit 255
fi

case "$1" in
    "start" )
        start;;
    "stop" )
        stop;;
    "run" )
        run;;
    "restart" )
        start
        stop;;
    "install" )
        install;;
    "uninstall" )
        uninstall;;
    "set_config" )
    	set_config;;
    "post_install" )
        post_install;;
    * )
        usage ;;
esac
